chore: move to new pre commit, remove pylint comments and add libpvarki

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,10 +1,10 @@
 on:
-    pull_request:
+  pull_request:
 
 jobs:
-    cfssl:
-      runs-on: ubuntu-latest
-      steps:
+  cfssl:
+    runs-on: ubuntu-latest
+    steps:
       - uses: actions/checkout@v4
       - run: docker build --target api -t rasenmaeher_cfssl .
       - run: docker run -d -p 8888:8888 --name rasenmaeher_cfssl rasenmaeher_cfssl
@@ -12,40 +12,40 @@ jobs:
       - run: echo 'print whole trace' && curl http://localhost:8888
       - run: echo 'verify cfssl title' && curl http://localhost:8888 | grep '<title>CFSSL</title>'
 
-    restwrapper:
-      runs-on: ubuntu-latest
-      permissions:
-        contents: write
-        pull-requests: write
-        checks: write
-      strategy:
-        matrix:
-          python-version: ["3.11"] # , "3.12"]
-      steps:
-        - uses: actions/checkout@v4
-        - name: Install uv
-          uses: astral-sh/setup-uv@v5
-        - name: Set up Python ${{ matrix.python-version }}
-          run: uv python install ${{ matrix.python-version }}
-        - name: Install dependencies
-          run: uv sync --frozen
-        - name: Do pre-commit checks (black, lint, mypy)
-          run: |
-            uv run prek run --all-files
-        - name: Test with pytest
-          run: |
-            uv run py.test -v --junitxml=pytest.xml
-        - name: Publish Test Report
-          uses: mikepenz/action-junit-report@v4
-          if: success() || failure() # always run even if the previous step fails
-          with:
-            report_paths: '**/pytest*.xml'
-            detailed_summary: true
-            check_name: 'JUnit report (local)'
+  restwrapper:
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+      pull-requests: write
+      checks: write
+    strategy:
+      matrix:
+        python-version: ["3.11"] # , "3.12"]
+    steps:
+      - uses: actions/checkout@v4
+      - name: Install uv
+        uses: astral-sh/setup-uv@v5
+      - name: Set up Python ${{ matrix.python-version }}
+        run: uv python install ${{ matrix.python-version }}
+      - name: Install dependencies
+        run: uv sync --frozen
+      - name: Do pre-commit checks (black, lint, mypy)
+        run: |
+          uv run prek run --all-files
+      - name: Test with pytest
+        run: |
+          uv run py.test -v --junitxml=pytest.xml
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: "**/pytest*.xml"
+          detailed_summary: true
+          check_name: "JUnit report (local)"
 
-    restwrapper_docker:
-      runs-on: ubuntu-latest
-      steps:
+  restwrapper_docker:
+    runs-on: ubuntu-latest
+    steps:
       - uses: actions/checkout@v4
       - run: mkdir -p /tmp/ca_public && touch /tmp/ca_public/crl.der
       - run: docker build --target ocsprest -t rasenmaeher_ocsprest .
