make CI run unit tests for the REST wrapper

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -11,3 +11,37 @@ jobs:
       - run: sleep 60 && docker logs rasenmaeher_cfssl
       - run: echo 'print whole trace' && curl http://localhost:8888
       - run: echo 'verify cfssl title' && curl http://localhost:8888 | grep '<title>CFSSL</title>'
+
+    restwrapper:
+      runs-on: ubuntu-latest
+      permissions:
+        contents: write
+        pull-requests: write
+        checks: write
+      strategy:
+        matrix:
+          python-version: ["3.11"] # , "3.12"]
+      steps:
+        - uses: actions/checkout@v3
+        - name: Set up Python ${{ matrix.python-version }}
+          uses: actions/setup-python@v4
+          with:
+            python-version: ${{ matrix.python-version }}
+        - name: Install dependencies
+          run: |
+            python -m pip install --upgrade pip
+            pip install poetry
+            poetry install
+        - name: Do pre-commit checks (black, lint, mypy)
+          run: |
+            poetry run pre-commit run --all-files
+        - name: Test with pytest
+          run: |
+            poetry run py.test -v --junitxml=pytest.xml
+        - name: Publish Test Report
+          uses: mikepenz/action-junit-report@v4
+          if: success() || failure() # always run even if the previous step fails
+          with:
+            report_paths: '**/pytest*.xml'
+            detailed_summary: true
+            check_name: 'JUnit report (local)'
